gulpFile.js
the watchify option has been changed to avoid the killing of the process whenever there's something add in the files
=> [WIP] changes in the gulpfile for watch

css/style.css, webpack/plugins.js
=> [RFR] Fix css error

demo/demo.js, lib/drawer/drops.js, lib/eventDrops.js, lib/zoom.js, test/karma/drawer/drops.js, test/karma/eventDrops.js
=> [RFR] Fix click, hover and zoomend event listeners

package.json
For confidentiality reasons, I didn't include any emails (except mine). If you want to add your's, feel free to add. :)
=> [RFR] Add a list of contributors in package.json

CHANGELOG, README.md, lib/config.js, lib/drawer/drops.js, test/karma/drawer/drops.js
=> [RFR] Implement `mouseout` event

lib/config.js, lib/eventDrops.js
Please consider these tweaks to make my life easier!  I do not want to maintain a fork.
Thanks for the awesome project; as we use the library more I hope to send a few more useful PRs.
=> Fixes #114: Participation in jspm/systemjs project not possible

.travis.yml, lib/drawer/drops.js, lib/drawer/index.js, lib/drawer/lineSeparator.js, lib/drawer/xAxis.js, lib/eventDrops.js, lib/xAxis.js, test/karma/drawer/drops.js
=> [RFR] Fix SVG viewport

.npmignore, package.json
And try to fix current published package which seems completly broken.
=> Improve bundling

src/zoom.js, test/karma/eventDrops.js, test/karma/zoom.js
Superseeds #133. Fixes #149.
I'm not yet fully satisfied by naming. Working on it before switching to RFR.
=> [RFR] Call `configuration.date` on zoom

.babelrc, Makefile, jest.config.js, package.json, src/axis.spec.js, testSetup.js, yarn.lock
Mergeable. I'll implement other tests in other PR.
=> [RFR] Bootstrap tests with Jest

src/bounds.js, src/bounds.spec.js, src/drop.spec.js, src/dropLine.spec.js
=> [WIP] Still more tests

.babelrc, Makefile, demo/demo.css, demo/demo.js, demo/index.html, package.json, src/__mocks__/zoom.js, src/config.js, src/index.js, src/index.spec.js, src/zoom.js, yarn.lock
=> [RFR] Expose `scale` and `filteredData` methods

README.md, docs/configuration.md, package.json
Keeping it as WIP as it misses several configuration parameters. It will be completed during their reimplementation.
=> [RFR] Update README

demo/demo.js, package.json, src/index.js, src/index.spec.js
Put configuration parameters and `d3` at same level.
``` diff
{
d3,
-    config: {
-        drop: { radius: 10 }
-    }
+    drop: { radius: 10 }
}
=> [RFR] Flatten configuration object

README.md, src/index.js, src/index.spec.js
=> [RFR] Fix scale method and expose draw function

CHANGELOG, MIGRATION-4.0.md
First draft. Will be improved over time.
=> [RFR] Write changelog and migration guide

README.md, package.json
=> [RFR] Fix documentation

README.md
Code for sample repositoriesData (line 54) missing closing brackets.
=> Update README with code sample fixes

docs/configuration.md
=> Fix configuration display

.github/ISSUE_TEMPLATE.md
=> [RFR] Add issue template

CHANGELOG, Makefile
=> [RFR] Publish automatically Git tag when publishing on npm

.github/ISSUE_TEMPLATE.md, README.md
=> [RFR] Clarifying readme

docs/configuration.md, package.json, src/__mocks__/indicator.js, src/config.js, src/dropLine.js, src/dropLine.spec.js, src/indicator.js, src/indicator.spec.js, src/isAfter.js, src/isAfter.spec.js, src/isBefore.js, src/isBefore.spec.js, src/withinRange.js, src/withinRange.spec.js
=> [RFR] Add "more-to-see" indicators when there is data hidden

src/dropLine.spec.js, src/indicator.js
=> [RFR] remove .only in test
